# Generated by Django 5.2 on 2025-05-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date_played',
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='TournamentMaker.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='TournamentMaker.pool'),
        ),
    ]
