# Generated by Django 5.2 on 2025-06-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='TournamentMaker.city'),
        ),
    ]
