# Generated by Django 5.2 on 2025-06-17 08:16

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
    model_name='match',
    name='next_match',
    field=models.ForeignKey(
        to='TournamentMaker.Match',
        null=True,
        blank=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name='previous_matches'
    ),
),

    ]
