# Generated by Django 5.2.2 on 2025-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='penalty_team_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='penalty_team_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
