# Generated by Django 5.2 on 2025-06-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
    ]
