# Generated by Django 5.2 on 2025-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
