# Generated by Django 5.2 on 2025-06-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Match en direct', max_length=100)),
                ('twitch_url', models.URLField(help_text="Lien d'intégration Twitch (ex: https://player.twitch.tv/?channel=ton_chaine&parent=localhost)")),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
