"""
# Generated by Django 5.2.1 on 2025-06-15 23:43

from django.db import migrations
from django.db import models



class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
    migrations.AddField(
        model_name='tournament',
        name='slug',
        field=models.SlugField(max_length=200, unique=True, blank=True),
    ),
]
"""
    
# Generated by Django 5.2.1 on 2025-06-15 23:43

from django.db import migrations, models
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    Tournament = apps.get_model('TournamentMaker', 'Tournament')
    db_alias = schema_editor.connection.alias

    for tournament in Tournament.objects.using(db_alias).all():
        base_slug = slugify(tournament.name)
        slug = base_slug
        suffix = 1
        while Tournament.objects.using(db_alias).filter(slug=slug).exclude(pk=tournament.pk).exists():
            slug = f"{base_slug}-{suffix}"
            suffix += 1
        tournament.slug = slug
        tournament.save()

class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, blank=True, null=True),
        ),
        migrations.RunPython(generate_unique_slugs),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
