# Generated by Django 5.2 on 2025-06-25 10:18

from django.db import migrations

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                to="TournamentMaker.address",
                null=True,
                blank=True,
                related_name="tournaments"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="latitude",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="longitude",
            field=models.FloatField(null=True, blank=True),
        ),
    ]
