# Generated by Django 5.2.1 on 2025-06-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="extra_time",
            field=models.BooleanField(
                blank=True, help_text="Prolongations possibles", null=True
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="half_time_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Durée de la mi-temps (en minutes)", null=True
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="match_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Durée d’un match (en minutes)", null=True
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="number_of_quarters",
            field=models.PositiveIntegerField(
                blank=True, help_text="Nombre de quart-temps", null=True
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="penalty_shootout",
            field=models.BooleanField(
                blank=True, help_text="Tirs au but en cas d’égalité", null=True
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="quarter_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Durée d’un quart-temps (en minutes)", null=True
            ),
        ),
    ]
