# Generated by Django 5.2 on 2025-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('pool', 'Phase de poule'), ('round_of_32', 'Seizième de finale'), ('eighth', 'Huitième de finale'), ('quarter', 'Quart de finale'), ('semi', 'Demi-finale'), ('final', 'Finale'), ('third_place', 'Petite finale')], default='pool', max_length=20),
        ),
    ]
