# Generated by Django 5.2.1 on 2025-06-15 23:43

from django.db import migrations
from django.db import models



class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0001_initial'),
    ]

    operations = [
    migrations.AddField(
        model_name='tournament',
        name='slug',
        field=models.SlugField(max_length=200, unique=True, blank=True),
    ),
]