# Generated by Django 5.2 on 2025-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0002_remove_match_date_played_pool_team_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pool',
        ),
        migrations.AddField(
            model_name='match',
            name='date_played',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
    ]
