# Generated by Django 5.2 on 2025-06-25 10:21

from django.db import migrations
from django.db import migrations

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0002_add_location_fields_to_tournament'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TournamentMaker.City')),
            ],
        ),
    ]
