# Generated by Django 5.2.2 on 2025-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0002_tournament_penalty_team_a_tournament_penalty_team_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='penalty_team_a',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='penalty_team_b',
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_team_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_team_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
