# Generated by Django 5.2.1 on 2025-06-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0002_add_slug_to_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
