# Generated by Django 5.2 on 2025-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0002_alter_tournament_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
