# Generated by Django 5.2 on 2025-06-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0003_alter_tournament_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner_side',
        ),
    ]
