# Generated by Django 5.2 on 2025-05-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0003_remove_team_pool_match_date_played_delete_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teams', models.ManyToManyField(blank=True, related_name='pools', to='TournamentMaker.team')),
            ],
        ),
    ]
