# Generated by Django 5.2 on 2025-06-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0003_address_alter_tournament_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default=75, max_length=10),
            preserve_default=False,
        ),
    ]
