# Generated by Django 5.2 on 2025-06-12 19:02

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0003_alter_userprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.OneToOneField(
                to='TournamentMaker.Organisateur',  # ← assure-toi que le modèle s'appelle bien ça
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='organized_tournament',
            ),
        ),
    ]
