# Generated by Django 5.2 on 2025-06-17 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0003_tournamentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentphoto',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TournamentMaker.tournament'),
        ),
    ]
