# Generated by Django 5.2 on 2025-05-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0004_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='TournamentMaker.pool'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
