# Generated by Django 5.2 on 2025-06-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0004_tournamentphoto_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
