# Generated by Django 5.2.1 on 2025-06-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0004_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='number_of_pools',
            field=models.IntegerField(default=0),
        ),
    ]
