# Generated by Django 5.2 on 2025-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0004_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='nb_sets_to_win',
            field=models.PositiveIntegerField(default=3, help_text='Nombre de sets nécessaires pour gagner un match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_per_set',
            field=models.PositiveIntegerField(default=25, help_text='Nombre de points nécessaires pour gagner un set'),
        ),
    ]
