# Generated by Django 5.2 on 2025-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0005_match_pool_alter_match_score_team_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date_played',
        ),
        migrations.RemoveField(
            model_name='match',
            name='pool',
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_b',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
