# Generated by Django 5.2.1 on 2025-06-07 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0005_tournament_number_of_pools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='TournamentMaker.pool'),
        ),
    ]
