# Generated by Django 5.2.1 on 2025-06-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0006_match_tournament_alter_organisateur_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "Débutant"),
                    (2, "Intermédiaire"),
                    (3, "Avancé"),
                    (4, "Expert"),
                    (5, "Maître"),
                ]
            ),
        ),
    ]
