# Generated by Django 5.2 on 2025-06-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0006_match_tournament_alter_organisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='TournamentMaker.team'),
        ),
    ]
