# Generated by Django 5.2.1 on 2025-06-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0005_tournament_nb_sets_to_win_tournament_points_per_set'),
        ('TournamentMaker', '0006_remove_pool_teams_team_pool'),
    ]

    operations = [
    ]
