# Generated by Django 5.2 on 2025-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0006_remove_match_date_played_remove_match_pool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='max_teams',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
