# Generated by Django 5.2 on 2025-05-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0007_pool_max_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='max_teams',
        ),
    ]
