# Generated by Django 5.2 on 2025-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0007_alter_match_team_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
