# Generated by Django 5.2.1 on 2025-06-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0007_merge_20250609_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='TournamentMaker.tournament'),
            preserve_default=False,
        ),
    ]
