# Generated by Django 5.2.1 on 2025-06-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0008_alter_pool_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('rugby', 'Rugby')], default='Football', max_length=50),
        ),
    ]
