# Generated by Django 5.2 on 2025-05-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0008_remove_pool_max_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='max_size',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
