# Generated by Django 5.2 on 2025-06-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0009_alter_tournament_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('round_robin', 'À la ronde'), ('knockout', 'Élimination directe')], default='round_robin', max_length=20),
        ),
    ]
