# Generated by Django 5.2 on 2025-06-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0007_alter_player_level'),
        ('TournamentMaker', '0009_alter_match_team_a'),
    ]

    operations = [
    ]
