# Generated by Django 5.2 on 2025-05-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0009_pool_max_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='TournamentMaker.pool'),
        ),
    ]
