# Generated by Django 5.2 on 2025-05-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0010_match_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score_team_a',
            new_name='set1_team_a',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_team_b',
            new_name='set1_team_b',
        ),
        migrations.AddField(
            model_name='match',
            name='set2_team_a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='set2_team_b',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='set3_team_a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='set3_team_b',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='set4_team_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='set4_team_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='set5_team_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='set5_team_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
