# Generated by Django 5.2.1 on 2025-06-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0003_alter_tournament_slug'),
        ('TournamentMaker', '0010_merge_0007_alter_player_level_0009_alter_match_team_a'),
    ]

    operations = [
    ]
