# Generated by Django 5.2 on 2025-05-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0003_ranking_losses_ranking_played_ranking_points_and_more'),
        ('TournamentMaker', '0011_rename_score_team_a_match_set1_team_a_and_more'),
    ]

    operations = [
    ]
