# Generated by Django 5.2.1 on 2025-06-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0011_merge_20250616_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='TournamentMaker.match'),
        ),
    ]
