# Generated by Django 5.2 on 2025-05-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0011_rename_score_team_a_match_set1_team_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_elimination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
