# Generated by Django 5.2 on 2025-05-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0011_rename_score_team_a_match_set1_team_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('men', 'Masculin'), ('women', 'Féminin'), ('mixed', 'Mixte')], default='men', max_length=10),
        ),
    ]
