# Generated by Django 5.2 on 2025-05-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0012_team_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
    ]
