# Generated by Django 5.2 on 2025-05-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0012_merge_20250520_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='played',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='points',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='wins',
        ),
        migrations.AlterField(
            model_name='ranking',
            name='rank',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TournamentMaker.team'),
        ),
    ]
