# Generated by Django 5.2 on 2025-05-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0012_match_is_elimination_match_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_elimination',
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
