# Generated by Django 5.2 on 2025-06-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0012_tournament_type_tournament_alter_tournament_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='type_tournament',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('rugby', 'Rugby')], default='Football', max_length=50),
        ),
    ]
