# Generated by Django 5.2 on 2025-06-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0013_remove_tournament_type_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type_tournament',
            field=models.CharField(choices=[('RR', 'Round Robin'), ('DE', 'Direct Elimination')], default='RR', max_length=2),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('rugby', 'Rugby')], default='football', max_length=50),
        ),
    ]
