# Generated by Django 5.2 on 2025-05-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0013_remove_match_is_elimination_alter_match_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='phase',
        ),
    ]
