# Generated by Django 5.2 on 2025-06-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0014_tournament_type_tournament_alter_tournament_sport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('round', 'start_time', 'id')},
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.PositiveSmallIntegerField(default=1, help_text='Journée / tour'),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé'), (4, 'Expert'), (5, 'Maître')]),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('pool', 'team_a', 'team_b')},
        ),
    ]
