# Generated by Django 5.2 on 2025-06-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0014_tournament_type_tournament_alter_tournament_sport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='department',
            new_name='city',
        ),
    ]
