# Generated by Django 5.2 on 2025-05-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0012_match_en_cours'),
        ('TournamentMaker', '0015_userprofile_date_of_birth_userprofile_email_and_more'),
    ]

    operations = [
    ]
