# Generated by Django 5.2.1 on 2025-06-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0016_alter_userprofile_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="player",
            name="level",
            field=models.CharField(
                choices=[
                    (1, "Débutant"),
                    (2, "Intermédiaire"),
                    (3, "Avancé"),
                    (4, "Expert"),
                    (5, "Maître"),
                ],
                max_length=1,
            ),
        ),
        migrations.RemoveField(
            model_name="match",
            name="round",
        ),
    ]
