# Generated by Django 5.2.1 on 2025-05-23 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0016_merge_20250521_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="tournament",
            name="is_indoor",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="sport",
            field=models.CharField(default="Football", max_length=50),
        ),
        migrations.AddField(
            model_name="tournament",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
