# Generated by Django 5.2 on 2025-06-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0015_alter_match_options_match_round_alter_player_level_and_more'),
        ('TournamentMaker', '0016_alter_userprofile_team'),
    ]

    operations = [
    ]
