# Generated by Django 5.2 on 2025-06-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0015_rename_department_tournament_city'),
        ('TournamentMaker', '0017_merge_20250611_1301'),
    ]

    operations = [
    ]
