# Generated by Django 5.2.1 on 2025-06-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0015_rename_department_tournament_city"),
        (
            "TournamentMaker",
            "0017_alter_match_options_alter_match_unique_together_and_more",
        ),
        ("TournamentMaker", "0017_merge_20250611_1301"),
    ]

    operations = []
