# Generated by Django 5.2 on 2025-05-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0017_pool_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='tournament',
        ),
    ]
