# Generated by Django 5.2 on 2025-06-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0018_merge_20250611_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='department',
            new_name='city',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé'), (4, 'Expert'), (5, 'Maître')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='TournamentMaker.team'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='round',
        ),
    ]
