# Generated by Django 5.2 on 2025-06-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0018_merge_20250611_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='city',
            new_name='department',
        ),
    ]
