# Generated by Django 5.2.1 on 2025-06-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0018_merge_20250612_0905"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="city",
            new_name="department",
        ),
    ]
