# Generated by Django 5.2 on 2025-05-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0017_remove_userprofile_date_of_birth_and_more'),
        ('TournamentMaker', '0019_pool_tournament'),
    ]

    operations = [
    ]
