# Generated by Django 5.2 on 2025-05-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0016_merge_20250521_1723'),
        ('TournamentMaker', '0019_pool_tournament'),
    ]

    operations = [
    ]
