# Generated by Django 5.2 on 2025-06-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0019_alter_match_options_and_more'),
        ('TournamentMaker', '0019_rename_city_tournament_department'),
    ]

    operations = [
    ]
