# Generated by Django 5.2 on 2025-06-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0019_alter_match_options_rename_department_city_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='city',
            new_name='department',
        ),
    ]
