# Generated by Django 5.2 on 2025-06-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0020_alter_match_team_a_alter_match_team_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='TournamentMaker.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match_slot',
            field=models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True),
        ),
    ]
