# Generated by Django 5.2 on 2025-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0020_merge_20250522_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='tournament',
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('pool', 'Phase de poule'), ('quarter', 'Quart de finale'), ('semi', 'Demi-finale'), ('final', 'Finale')], default='pool', max_length=10),
        ),
    ]
