# Generated by Django 5.2 on 2025-05-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0021_remove_pool_tournament_match_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterFinalMatch',
            fields=[
            ],
            options={
                'verbose_name': 'Match Quart de Finale',
                'verbose_name_plural': 'Matchs Quart de Finale',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TournamentMaker.match',),
        ),
        migrations.RemoveField(
            model_name='match',
            name='phase',
        ),
    ]
