# Generated by Django 5.2 on 2025-06-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0019_alter_match_options_and_more'),
        ('TournamentMaker', '0021_match_next_match_match_next_match_slot'),
    ]

    operations = [
    ]
