# Generated by Django 5.2 on 2025-05-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0022_quarterfinalmatch_remove_match_phase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuarterFinalMatch',
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('pool', 'Phase de poule'), ('quarter', 'Quart de finale'), ('semi', 'Demi-finale'), ('final', 'Finale')], default='pool', max_length=10),
        ),
    ]
