# Generated by Django 5.2 on 2025-05-22 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0023_delete_quarterfinalmatch_match_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TournamentMaker.team')),
            ],
        ),
    ]
