# Generated by Django 5.2 on 2025-05-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0024_knockoutranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnockoutRanking',
        ),
    ]
