# Generated by Django 5.2 on 2025-05-22 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0025_delete_knockoutranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRankingProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ranking Final',
                'verbose_name_plural': 'Ranking Final',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TournamentMaker.ranking',),
        ),
    ]
