# Generated by Django 5.2 on 2025-05-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0017_tournament_address_tournament_end_date_and_more'),
        ('TournamentMaker', '0026_finalrankingproxy'),
    ]

    operations = [
    ]
