# Generated by Django 5.2 on 2025-05-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0027_merge_20250526_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('pool', 'Phase de poule'), ('quarter', 'Quart de finale'), ('semi', 'Demi-finale'), ('final', 'Finale'), ('third_place', 'Petite finale')], default='pool', max_length=20),
        ),
    ]
