# Generated by Django 5.2 on 2025-05-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0028_alter_match_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='captain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
