# Generated by Django 5.2 on 2025-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0028_alter_match_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
