# Generated by Django 5.2.1 on 2025-05-26 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0028_alter_match_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="TournamentMaker.tournament",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pools",
                to="TournamentMaker.tournament",
            ),
        ),
    ]
