# Generated by Django 5.2 on 2025-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0028_alter_match_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='en_cours',
        ),
        migrations.AddField(
            model_name='match',
            name='statut',
            field=models.CharField(choices=[('ND', 'Non débuté'), ('EC', 'En cours'), ('T', 'Terminé')], default='ND', max_length=2),
        ),
    ]
