# Generated by Django 5.2 on 2025-05-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0029_match_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ordre',
        ),
    ]
