# Generated by Django 5.2 on 2025-05-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0029_remove_match_en_cours_match_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
    ]
