# Generated by Django 5.2 on 2025-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0030_remove_team_captain_email_remove_team_captain_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé'), (4, 'Expert'), (5, 'Maître')], max_length=1),
        ),
    ]
