# Generated by Django 5.2 on 2025-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0030_remove_match_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé'), (4, 'Expert'), (5, 'Maître')], default=1),
        ),
    ]
