# Generated by Django 5.2 on 2025-05-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0031_terrain_match_terrain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='terrain',
        ),
        migrations.DeleteModel(
            name='Terrain',
        ),
    ]
