# Generated by Django 5.2 on 2025-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0032_remove_match_terrain_delete_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='terrain_number',
            field=models.CharField(blank=True, choices=[('1', 'Terrain 1'), ('2', 'Terrain 2'), ('3', 'Terrain 3'), ('4', 'Terrain 4'), ('5', 'Terrain 5'), ('6', 'Terrain 6')], max_length=1, null=True, verbose_name='Terrain'),
        ),
    ]
