# Generated by Django 5.2 on 2025-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0034_match_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='winner_side',
            field=models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True, verbose_name='Vainqueur'),
        ),
    ]
