# Generated by Django 5.2 on 2025-05-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0030_remove_match_ordre'),
        ('TournamentMaker', '0035_remove_match_winner_match_winner_side'),
    ]

    operations = [
    ]
