# Generated by Django 5.2 on 2025-05-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0031_alter_player_level'),
        ('TournamentMaker', '0036_merge_20250527_2046'),
    ]

    operations = [
    ]
