# Generated by Django 5.2 on 2025-05-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0013_remove_team_category'),
        ('TournamentMaker', '0037_merge_20250527_2055'),
    ]

    operations = [
    ]
