# Generated by Django 5.2.1 on 2025-06-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0038_merge_20250528_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match_type',
            field=models.CharField(choices=[('sets', 'Match en sets (ex: volley)'), ('classic', 'Match classique (ex: foot)')], default='classic', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='nb_players_per_team',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='nb_pools',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='nb_teams',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='nb_terrains',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pool_phase_type',
            field=models.CharField(choices=[('yes', 'Round Robin'), ('no', 'Pas Round Robin')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('rugby', 'Rugby')], default='football', max_length=50),
        ),
    ]
