# Generated by Django 5.2.1 on 2025-06-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0029_match_tournament_pool_tournament"),
        ("TournamentMaker", "0038_merge_20250528_2109"),
    ]

    operations = []
