# Generated by Django 5.2.1 on 2025-06-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TournamentMaker", "0039_merge_20250602_1357"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="tournament",
        ),
    ]
