# Generated by Django 5.2.1 on 2025-06-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0039_tournament_match_type_tournament_nb_players_per_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='match_type',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='nb_players_per_team',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='nb_pools',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='nb_teams',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='nb_terrains',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='pool_phase_type',
        ),
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='TournamentMaker.tournament'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.CharField(default='Football', max_length=50),
        ),
    ]
