# Generated by Django 5.2.1 on 2025-06-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0040_remove_tournament_match_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
    ]
