# Generated by Django 5.2.1 on 2025-06-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentMaker', '0041_remove_player_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='TournamentMaker.tournament'),
            preserve_default=False,
        ),
    ]
